import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export const generateSessionPDF = (logs, title = "Session Report") => {
    const doc = new jsPDF();
    const primaryColor = '#0C7B5E'; // Teal
    const textColor = '#1e293b'; // slate-800
    const lightGray = '#f8fafc'; // slate-50
    
    // Document Header (Teal Background)
    doc.setFillColor(primaryColor);
    doc.rect(0, 0, doc.internal.pageSize.width, 35, 'F');
    
    doc.setTextColor('#ffffff');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text('MediSign', 14, 22);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Medical Sign Language Recognition', 14, 28);
    
    // Date & Time (Top Right)
    const today = new Date();
    doc.setFontSize(10);
    doc.text(`Date: ${today.toLocaleDateString()}`, doc.internal.pageSize.width - 14, 20, { align: 'right' });
    doc.text(`Time: ${today.toLocaleTimeString()}`, doc.internal.pageSize.width - 14, 26, { align: 'right' });
    
    // Report Title
    doc.setTextColor(textColor);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 14, 50);
    
    // Configure table data
    const tableColumn = ["Date & Time", "Medical Sign", "Confidence", "Language", "Translation"];
    const tableRows = [];

    logs.forEach(log => {
        const logData = [
            log.time || '--',
            log.term || '--',
            `${(log.confidence * 100).toFixed(1)}%`,
            log.language ? log.language.toUpperCase() : 'EN',
            log.translation || '--'
        ];
        tableRows.push(logData);
    });

    // Generate Table
    doc.autoTable({
        startY: 60,
        head: [tableColumn],
        body: tableRows,
        theme: 'grid',
        headStyles: {
            fillColor: primaryColor,
            textColor: '#ffffff',
            fontStyle: 'bold',
            halign: 'center'
        },
        styles: {
            font: 'helvetica',
            fontSize: 10,
            textColor: textColor,
            cellPadding: 6
        },
        alternateRowStyles: {
            fillColor: lightGray
        },
        columnStyles: {
            0: { cellWidth: 40 },
            1: { cellWidth: 45, fontStyle: 'bold' },
            2: { cellWidth: 30, halign: 'center' },
            3: { cellWidth: 25, halign: 'center' },
            4: { cellWidth: 'auto' }
        }
    });

    // Footer with Versioning
    const pageCount = doc.internal.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(9);
        doc.setTextColor('#94a3b8'); // slate-400
        doc.text(
            'Generated by MediSign v2.0',
            doc.internal.pageSize.width / 2,
            doc.internal.pageSize.height - 10,
            { align: 'center' }
        );
    }

    // Trigger File Save
    doc.save(`MediSign_Report_${today.getTime()}.pdf`);
};
